from typing import Any, TypeVar

_E = TypeVar("_E", bound="BaseElement")

class BaseElement:
    attribs: dict[str, Any]
    elements: list[Any]
    def __init__(self, **extra: Any) -> None: ...
    def add(self, element: _E) -> _E: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
