name: Build Documentation using MkDocs

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --with docs

      - name: Deploy
        run: |
          poetry run mkdocs gh-deploy
